import "./globals.css";
import {
  Roboto_Condensed,
  Bricolage_Grotesque,
  DM_Sans,
} from "next/font/google";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bricolage",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dmsans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${robotoCondensed.variable} ${bricolageGrotesque.variable} ${dmSans.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
